### ISSUE TITLE
Safari, YAbrowser can't save profile information

### ISSUE THREAD

**Issue by tvorogme** [tvorogme/gotosite#42]
In safari you can't save information...

**Comment by tvorogme** [comment]
YAbrowser also not working

**Comment by Andrewerr** [comment]
Safari show following in the console after call save():
[Error] TypeError: undefined is not a function (near '...}).autocomplete({...')
	add_autocomplite_city (autocomplite.js:61)
	global code (autocomplite.js:77)

**Comment by tvorogme** [comment]
Fix it!
